CREATE TABLE `installmentOrders` (
	`id` int AUTO_INCREMENT NOT NULL,
	`orderNumber` varchar(48) NOT NULL,
	`userId` int,
	`shopifyCartId` varchar(255),
	`productTitle` varchar(255) NOT NULL,
	`productHandle` varchar(255),
	`gift` varchar(120) NOT NULL,
	`priceUsd` decimal(10,2) NOT NULL,
	`priceSyp` decimal(14,0) NOT NULL,
	`downPaymentUsd` decimal(10,2) NOT NULL,
	`downPaymentSyp` decimal(14,0) NOT NULL,
	`discountPercent` int NOT NULL DEFAULT 0,
	`months` int NOT NULL,
	`monthlyInstallmentUsd` decimal(10,2) NOT NULL,
	`monthlyInstallmentSyp` decimal(14,0) NOT NULL,
	`eligibilityStatus` enum('eligible','review_required') NOT NULL,
	`status` enum('new','under_review','approved','needs_contact','cancelled') NOT NULL DEFAULT 'new',
	`customerName` varchar(160) NOT NULL,
	`age` int NOT NULL,
	`jobNature` varchar(160) NOT NULL,
	`province` varchar(80) NOT NULL,
	`area` varchar(120) NOT NULL,
	`landmark` varchar(255),
	`recipientName` varchar(160) NOT NULL,
	`phone` varchar(32) NOT NULL,
	`alternatePhone` varchar(32),
	`paymentMethod` enum('sham_cash') NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `installmentOrders_id` PRIMARY KEY(`id`),
	CONSTRAINT `installmentOrders_orderNumber_unique` UNIQUE(`orderNumber`)
);
